apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: puraai-ingress
  namespace: pura-ai
spec:
  rules:
    - host: api.puraai.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: puraai-service
                port:
                  number: 80
